### ISSUE TITLE
Funnel not exposed to internet

### ISSUE THREAD

**Issue by vysecurity** [tailscale-dev/tclip#25]
I deployed the code with Funnel to Fly and it could not be accessed from the internet from outside of my Tailnet.

I noticed that the DNS did not even resolve so there's no way it could even try to connect.

Tailscale has a green note saying `FUNNEL`.

**Comment by Xe** [comment]
That's weird. Do you have the right [node attribute](https://tailscale.com/kb/1223/tailscale-funnel/?ref=refind#node-attribute-required) set on that node?

**Comment by vysecurity** [comment]
@Xe are you referring to the following? 
![Safari-2023-08-23 at 13 59 10@2x](https://github.com/tailscale-dev/tclip/assets/3596242/766cf9c1-10a0-4694-80e3-b24ee003df36)

**Comment by Xe** [comment]
Is your tclip node tagged? If it's tagged it won't match `autogroup:member`.

**Comment by vysecurity** [comment]
Yep it’s tagged but I also put tag:pastebin in the ACL and also on the pastebin box.

**Comment by Erisa** [comment]
Hi @vysecurity - sorry for the delay here. I'm going to close this issue for now as it's been a while, **however** if you are still having this issue on the latest version of `tclip` could you reopen and share more details here on your setup so we can reproduce? Adding `-tsnet-verbose` / `TSNET_VERBOSE` may also help surface more logs.  
On the other hand if this is an issue with your tailnet / not specifically tclip, please feel free to open a ticket with [support](https://tailscale.com/contact/support) and we can take a look.!
