### ISSUE TITLE
Suggestion: Hide users' names from Funnel

### ISSUE THREAD

**Issue by RuiNtD** [tailscale-dev/tclip#31]
The owner of a paste should only be shown to users of the Tailnet, especially since most Tailscale users will probably be using OAuth, revealing their full name and personal profile picture in most cases.

**Comment by RuiNtD** [comment]
Any update to this? I want to use tclip as my regular clip service, but I can't do so because I don't want to dox myself. 😂

**Comment by gmemstr** [comment]
@RuiNtD I've added this to my fork https://github.com/gmemstr/tclip/commit/6e59918938d49750741f9b1070918494b253f602, I don't believe this repo is maintained since Xe left Tailscale.
