### ISSUE TITLE
Suggestion: word wrapping

### ISSUE THREAD

**Issue by mikaelf** [tailscale-dev/tclip#42]
It would be very useful with word wrapping, especially when reading pastes on a mobile device. 

Perhaps word wrap could be enabled by default on narrow viewports and possible to control with a toggle.

**Comment by lucasew** [comment]
I just tested in my instance

If you create your note as a .md file it does word wrapping automatically

**Comment by lucasew** [comment]
Another tip

If you add /raw at the end of the URL, it will load the content as text directly and that will also word wrap.

**Comment by mikaelf** [comment]
Thanks!

**Comment by Erisa** [comment]
Hi @mikaelf! Sorry for the radio silence on this issue.
As of https://github.com/tailscale-dev/tclip/commit/f843ec5cd691712fe0930e0a05c7979e1b440c53 you can enable a new setting `ENABLE_WORD_WRAP` to enable word wrap. All options are listed here: <https://github.com/tailscale-dev/tclip?tab=readme-ov-file#configuration>

**Comment by mikaelf** [comment]
Thank you @Erisa! Haven't used `tclip` in quite a while due to this issue + the tailscale version being a bit behind, but as both of these issues have been fixed I'll give it another try.
