### ISSUE TITLE
Bump software versions ?

### ISSUE THREAD

**Issue by garfieldairlines** [tailscale-dev/tclip#50]
Hello,

I just got on my tailscale console that tailscale is 5 versions behind. Is it possible to update the packages on the docker image ?

Thanks.

**Comment by stevetrease** [comment]
It would be great if the underlying tailscale version could be kept up to date for this tool.

**Comment by gmemstr** [comment]
I've forked tclip and updated the deps https://github.com/gmemstr/tclip - I don't think this repo is really maintained anymore since Xe is no longer at Tailscale.

**Comment by gmemstr** [comment]
@garfieldairlines Of course! The pipeline publishes to https://github.com/gmemstr/tclip/pkgs/container/tclip, I also have `arm` images built on my private forge https://git.gmem.ca/arch/-/packages/container/tclip/latest

**Comment by Erisa** [comment]
Sorry for the radio silence here! I am going to be picking this up and bumping software versions later today.

**Comment by Erisa** [comment]
Resolved (for now) in #53
